### ISSUE TITLE
Det står "Ingen er påmeldt" på arrangementer som ikke krever påmelding

### ISSUE THREAD

**Issue by simoneby** [webkom/lego#1306]
Da ser det ut som om ingen vil komme på eventet. Gjelder bl.a. alle LaBamba sine eventer

**Comment by SmithPeder** [comment]
This was fixed in https://github.com/webkom/lego-webapp/pull/1390 , forgot to tag this issue.

Events with no mandetory registation now say 'Åpent arrangement'
<img width="643" alt="screenshot 2019-01-30 at 18 54 03" src="https://user-images.githubusercontent.com/23152018/52001829-a447cb00-24c0-11e9-9c6f-f3f9305314c9.png">
