### ISSUE TITLE
Pagination makes SSR with internal url impossible

### ISSUE THREAD

**Issue by orhanhenrik** [webkom/lego#1387]
SSR breaks pagination because next page url is invalid. This is because ssr talks to api over a different domain than the public one.

**Comment by odinuge** [comment]
This is a result of:
https://github.com/webkom/lego-webapp/blob/master/app/utils/createEntityReducer.js#L88

The cursor should be extracted (or the backend should be changed to return only the cursor), in order to support different endpoints. There should be no need to go through the firewall/haproxy etc. for the server side renderer.

**Comment by odinuge** [comment]
Using internal urls in the server side rendering atm. The pagination strategy should be fixes, so we can enable it again.

**Comment by LudvigHz** [comment]
Fixed in https://github.com/webkom/lego-webapp/pull/2009
