### ISSUE TITLE
Test failed randomly

### ISSUE THREAD

**Issue by JonasBak** [webkom/lego#1487]
When [testing in ci a random test failed](https://ci.abakus.no/webkom/lego/2580/7), afaik this has nothing to do with what I was changing and I simply had to rerun the test on the same commit for it to pass.

I know there has been some issues where we actually clone the commit that came before the one we're testing, but the commit that was before this one was already in master and prod

**Comment by edvardvb** [comment]
Looks like it failed because of the ordering in a list in https://github.com/webkom/lego/blob/master/lego/apps/contact/tests/test_send.py#L155

The test uses a `send`-method to send the email, which in turn has a function for fetching the recipients. This is done by fetching all memberships of the recipient group (HS, Webkom, etc.) with the leader role, and selecting the user for these memberships. 

https://github.com/webkom/lego/blob/master/lego/apps/contact/send.py#L42

I can't seem to find any specific ordering for the `Membership`- and `User`-models, so the order of the list is probably either random or based on `id`/`created_at`. If there is a defined ordering we should ensure that this is deterministic. If not, the test should be written to pass no matter what order the list is returned in.
