### ISSUE TITLE
Opened for some <TIME> ago not working as intended.

### ISSUE THREAD

**Issue by SmithPeder** [webkom/lego#1654]
When creating this component the wish was for events like **Bankett - itDAGENE 2019** should still be in the list as "Åpnet for 50 min ago", but here the event is removed the instant the admission opens. I think there is a bug in the logic here.

![image](https://user-images.githubusercontent.com/23152018/63685619-1e92c080-c800-11e9-8332-5ab773766cf3.png)

**Comment by odinuge** [comment]
Need more context

**Comment by odinuge** [comment]
Hi @SmithPeder,

Thanks for the additional context.

This is most likely because you have signed up for the event you are "missing" in the list. It is a feature that only events you _can_ sign up for is on the list, therefore events you cannot register to are not visible. This also includes events you have signed up for.

Feel free to close if this answers your question. :smile:

**Comment by SmithPeder** [comment]
I concur
