### ISSUE TITLE
Disable the option to react when not logged in.

### ISSUE THREAD

**Issue by kotlarz** [webkom/lego#1661]
We can still show the reactions, just have to disable the reaction picker and disable the option to click on reactions to react/unreact.

**Comment by kotlarz** [comment]
I need some input on this.

Should visitors be able to view the reactions without being logged in? The comments are hidden if the visitor/user isn't logged in. However, the comments are available through the API since the visitor has access to the content (i.e. an article), so we're actually just hiding them in the frontend.

Should the same be done with reactions? Or is it okay to view them, just not react?

**Comment by orhanhenrik** [comment]
Maybe reactions can have the same permissions as the parent entity, since they are anonymized and are fetched as part of the entity. Similarly I think comment count could be shown when not logged in.  

But I don't see a reason to show actual comments with names of people without being logged in. Since it's not visible on the website, the API permissions should also be changed.

**Comment by kotlarz** [comment]
That was exactly what I was thinking, cheers.

And yes, the API permissions aren't exactly perfect :upside_down_face:

**Comment by eikhr** [comment]
Fixed in https://github.com/webkom/lego-webapp/pull/1974 , not sure what the permissions are but reacting when not logged in is not possible.
