### ISSUE TITLE
Users with adjusted clocks are able to see the register button and captcha before events starts

### ISSUE THREAD

**Issue by AdrianAndersen** [webkom/lego#1684]
The request to join the event is stopped by the backend, and returns an error. This could be fixed if the timer on the event page use server time, rather than system time.

**Comment by hanswilw** [comment]
We have discussed this earlier and decided not to do anything with it. There were issues with timing of when the register button was shown since we have a countdown, and figured it was better by doing system clock evaluations continuously in the JS. Clients usually sync their system clock to a NTP server anyways, and if they try to glitch the system by changing their clock it returns an error as you mention.
However, if you figure out a sweet way of synchronising it – have a crack at it!

**Comment by hanswilw** [comment]
Looks like something like https://github.com/enmasseio/timesync could be viable though 👍

**Comment by kotlarz** [comment]
This has been reported by others, and I can see how annoying it can be as you end up in the waiting list. Fixing this would be great!
