### ISSUE TITLE
Polls percentage value is outside divs on 

### ISSUE THREAD

**Issue by AdrianAndersen** [webkom/lego#1686]
Ref: https://abakus.no/polls/13

**Comment by SmithPeder** [comment]
I guess the same calculations putting them outside on the frontpage(intentional)
![image](https://user-images.githubusercontent.com/23152018/65337571-b5b52300-dbc8-11e9-8093-853231b0a750.png)
is putting them outside on the detailed view of the poll
![image](https://user-images.githubusercontent.com/23152018/65337628-cebdd400-dbc8-11e9-95e1-bcf75198e8aa.png)
It simply looks if the number is less then 18
https://github.com/webkom/lego-webapp/blob/d002f46fa8c86d11f1e6ecd766df81dd3eba3866/app/components/Poll/index.js#L150-L153
