### ISSUE TITLE
Limit #weekly-articles to only one space on the front page

### ISSUE THREAD

**Issue by Magssch** [webkom/lego#1731]
Currently, if #weekly-articles are pinned, #weekly-articles will cover a lot of space on the front page. I suggest disallowing #weekly-articles to be pinned, or at least automatically remove the dedicated #weekly-module temporarily if a new #weekly is pinned. The same article should also never be shown more than once on the front page. I realize that this is in great part due to human error, but it would be very nice if we could somehow make the process of creating weekly articles a bit more streamlined, to avoid duplicates. See attached screenshot
![image](https://user-images.githubusercontent.com/37403247/69501885-9a88cb80-0f09-11ea-8b5d-c0f350bdbc28.png)

**Comment by JonasBak** [comment]
What makes an article a `#weekly`, as opposed to any other article, is the `weekly` tag.

If you look in the picture, you can see that the pinned article doesn't have the tag, which makes it behave just like a normal article. Which means that (IMO) this is just a user error.

To be able to stop `#weekly` from being pinned we would have to distinguish them somehow, which we do with the tag, so if people forget to tag the article we can't do anything, and if people remember, we don't have this problem.

We could look into having a "select article type" thing when creating an article, like we have with events, but I feel like it's just as easy to just remember to add one tag to the article.

**Comment by Magssch** [comment]
Yes it is obviously due to human error, but if we could make #weekly more of a special case (as it has its own module), I think we could avoid a lot of errors and mistakes. I still think we should disable pinning for weekly-articles, or at least temporarily disable the separate weekly-module if a weekly-article is pinned, as we have a lot of content and instead of showing duplicate information we should prioritize making as much content easily and instantly visible to the user.

**Comment by JonasBak** [comment]
There really isn't a "weekly-module", the weekly under the "Weekly" title just shows the last article tagged with `weekly`.

My point is that the reason why there seems to be 3 weekly articles in the picture is because the pinned one (which also shows up under "Artikler") isn't actually a weekly article, as it isn't tagged properly (there is another article in the "weekly-module"). So even if we disallowed pinning of weekly articles, or hid the "weekly-module", this (what happened in the picture) would still happen.

We _could_ make weekly into a whole other "entity" than articles, but this is IMO a lot more work than that the people that upload weekly just remember to tag the article.

**Comment by SmithPeder** [comment]
#brukerfeil
