### ISSUE TITLE
Better notification separation 

### ISSUE THREAD

**Issue by Arashfa0301** [webkom/lego#2894]
I am in favour of adding separators between the notifications, or any form for separation. In some cases, like the picture below, I believe it is annoying to distinguish between the different notifications.

<img width="421" alt="Screenshot 2022-08-29 at 17 11 35" src="https://user-images.githubusercontent.com/90712892/187237345-3855b217-5926-4c0e-ac12-55b89c795861.png">

**Comment by ingraso** [comment]
Would it help to move the icons to the top of the messages, so they're separated by the combination between the icon and sender (red text)?

How it looks today:
![Screenshot from 2022-08-30 12-30-04](https://user-images.githubusercontent.com/43182025/187415086-c850150d-756f-48be-8ba2-54cd6f873598.png)

Suggestion:
![Screenshot from 2022-08-30 12-31-27](https://user-images.githubusercontent.com/43182025/187415081-477f41df-ff6d-4ef0-93c4-3189f54d7d42.png)

**Comment by ivarnakken** [comment]
I think the replacement of the icons is a good change, but I also think it would benefit from getting slightly different backgrounds on every other notification.

**Comment by haukkagu** [comment]
Could this be a solution? I moved the icons to the top of each notification like suggested and added a border between each notification.

![solution](https://user-images.githubusercontent.com/66320400/191370227-bdb629d0-c0ab-4318-8c6e-8d87e1474495.png)

The spacing between each notification might be too big (among other nitpicks), but if you guys approve of the overall design/look, I can tweak it further.

**Comment by ivarnakken** [comment]
Thanks for the input, @haukkagu! ❤️ 

Do you think giving every other notification a slightly different background would look good? 

The spacing under the border is a bit much in my opinion. I would prefer some slightly more spacing on the left side between the icons and the edge though.

Perhaps also changing up the styling of the author and the title text so that there's less eye-catching red text? I don't think they must share the same styling.

**Comment by haukkagu** [comment]
closed by webkom/lego-webapp#3122
