### ISSUE TITLE
Semesters are missing from interest form e-mails

### ISSUE THREAD

**Issue by edvardvb** [webkom/lego#897]
It seems that the signal to the feed handler is triggered before the semesters are stored on the model? The semesters show up when viewing the interest later, but are not present when the email is generated. Could this have happened after the changes to semesters, @odinuge?

A quick fix would be to send the email during creation, instead of in the feed handler.

**Comment by odinuge** [comment]
The reason is that many-to-many relations (eg. semesters in companyInterest) are created after the `post_save` hook that is use to send notifications via the feed. It shouldn't be any problem to use the `m2m-changed` signal instead (fired when m2m-relations are saved/changed) - but it would require some changes in the general feed handling flow.

https://docs.djangoproject.com/en/dev/ref/signals/#m2m-changed

**Comment by edvardvb** [comment]
Why did this work previously then? :thinking:
