### ISSUE TITLE
HTTP 504 Gateway Timeout when accessing event without being logged in

### ISSUE THREAD

**Issue by kapteinstein** [webkom/lego#925]
Don't know if this is the right place to post this issue, so please close it if it is unrelated to webkom/lego. When I try to directly access an event without being logged in, eg. https://abakus.no/events/2125, the server responds with a HTTP 504 - Gateway Timeout error generated by 'Whale Platform'. See below for the (partial) request/response.

I think the expected behavior would be to either redirect the user to a login page, or let the user view the event but remain unable to sign up until they have logged in. 

```
GET /events/2125 HTTP/1.1
Host: abakus.no
Connection: keep-alive
Cache-Control: max-age=0
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3256.0 Safari/537.36
Upgrade-Insecure-Requests: 1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8

HTTP/1.1 504 Gateway Timeout
Server: nginx/1.13.5
Date: Thu, 02 Nov 2017 14:10:32 GMT
Content-Type: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Content-Length: 1674
Strict-Transport-Security: max-age=31536000;
```

**Comment by kapteinstein** [comment]
Well, i dunno what was happening earlier today, but it seems that the issue has been resolved. The URL is now returning a 404, which is as expected I guess.

**Comment by odinuge** [comment]
Hi Erik, 

Thanks for the bug report!

This was a frontend issue, temporary solved in https://github.com/webkom/lego-webapp/pull/877 (pushed to prod a few hours ago).

The timeouts occurred when the server side renderer (aka SSR) got a bad request, and our error reporting tool tried to log the error using a browser specific function that isn't supported not supported by node.js; making it crash. This issue was fixed in https://github.com/webkom/lego-webapp/pull/920.
